/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.ventana;

/**
 *
 * @author benja
 */
public class InterfazBus extends javax.swing.JFrame {

    /**
     * Creates new form InterfazAdmin
     */
    public InterfazBus() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SearchBusButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        AddBusButton = new javax.swing.JButton();
        DeleteBusFromCityButton = new javax.swing.JButton();
        ShowBusesFromCityButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SearchBusButton.setBackground(new java.awt.Color(0, 204, 51));
        SearchBusButton.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        SearchBusButton.setForeground(new java.awt.Color(255, 255, 255));
        SearchBusButton.setText("Buscar Bus");
        SearchBusButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SearchBusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchBusButtonMouseClicked(evt);
            }
        });
        SearchBusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBusButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SearchBusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 180, 60));

        jPanel2.setBackground(new java.awt.Color(0, 102, 0));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Menú de Administrador");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(33, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(17, 17, 17)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 800, 100));

        AddBusButton.setBackground(new java.awt.Color(0, 204, 51));
        AddBusButton.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        AddBusButton.setForeground(new java.awt.Color(255, 255, 255));
        AddBusButton.setText("Agregar Bus");
        AddBusButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AddBusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddBusButtonMouseClicked(evt);
            }
        });
        AddBusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBusButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AddBusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 180, 60));

        DeleteBusFromCityButton.setBackground(new java.awt.Color(0, 204, 51));
        DeleteBusFromCityButton.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        DeleteBusFromCityButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteBusFromCityButton.setText("Eliminar Bus");
        DeleteBusFromCityButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DeleteBusFromCityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBusFromCityButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteBusFromCityButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 180, 60));
        DeleteBusFromCityButton.getAccessibleContext().setAccessibleName(" Manejar\nCiudades");

        ShowBusesFromCityButton.setBackground(new java.awt.Color(0, 204, 51));
        ShowBusesFromCityButton.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        ShowBusesFromCityButton.setForeground(new java.awt.Color(255, 255, 255));
        ShowBusesFromCityButton.setText("Mostrar Buses");
        ShowBusesFromCityButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ShowBusesFromCityButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowBusesFromCityButtonMouseClicked(evt);
            }
        });
        jPanel1.add(ShowBusesFromCityButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 180, 60));

        BackButton.setBackground(new java.awt.Color(0, 204, 51));
        BackButton.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        BackButton.setForeground(new java.awt.Color(255, 255, 255));
        BackButton.setText("Volver");
        BackButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });
        jPanel1.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchBusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBusButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBusButtonActionPerformed

    private void AddBusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBusButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddBusButtonActionPerformed

    private void DeleteBusFromCityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBusFromCityButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteBusFromCityButtonActionPerformed

    private void AddBusButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBusButtonMouseClicked
        
    }//GEN-LAST:event_AddBusButtonMouseClicked

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        // TODO add your handling code here:
        InterfazAdmin backFrame = new InterfazAdmin ();
        backFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackButtonMouseClicked

    private void SearchBusButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchBusButtonMouseClicked
        
    }//GEN-LAST:event_SearchBusButtonMouseClicked

    private void ShowBusesFromCityButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowBusesFromCityButtonMouseClicked
        
    }//GEN-LAST:event_ShowBusesFromCityButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void mainWindow() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazBus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBusButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton DeleteBusFromCityButton;
    private javax.swing.JButton SearchBusButton;
    private javax.swing.JButton ShowBusesFromCityButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
